server:
  port: 8082

spring:
  application:
    name: kafka-demo-app
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: ticktok
        eventIn:
          destination: event
        pvin:
          destination: pageviewevent
        #pcin:
        #  destination: pcs
        output:
          destination: ticktok
        eventOut:
          destination: event
        pvout:
          destination: pageviewevent
        #pcout:
        #  destination: pcs



